### PR TITLE
Use common API for echo requests

### PR DESCRIPTION
**Pull request by mckennagalvin**
This pull request is a little long but it's hard to make the changes any smaller without breaking something, sorry!

This changes the server to use the common Request/Response/RequestHandler APIs. Right now I only implemented the bare minimum needed to get a basic Echo response.

Some of the things that still need to be done:
- Use the uri prefix to determine which handler to handle the request
- Implement RequestHandlerStatic
- Robust error handling
- Implement Request::Parse (our old request parser no longer works since we had it parse things while data was coming in -- we should probably just scrap it and implement something more straightforward)
- Write the 404 and status error handlers

Also all of our unit tests will basically be nonfunctional now.... haha so we probably need to redo all of those yay fun times

### CODE REVIEW

**Comment by mattdrag** [comment]
Ah yes, redoing unit testing is always my favorite part!

**Comment by mattdrag** [comment]
Hey McKenna, getting an error when I try and make the server. 

src/main.cpp: In function ‘void get_server_options(NginxConfig, http::server::server_options*)’:
src/main.cpp:53:66: error: cannot convert ‘std::unique_ptr<NginxConfig>*’ to ‘std::map<std::basic_string<char>, NginxConfig*>::mapped_type {aka NginxConfig*}’ in assignment
         server_options_pointer->static_handlers[statement.at(1)] = &config_line->child_block_;
                                                                  ^
make: *** [webserver] Error 1

**Comment by mattdrag** [comment]
Fixed the error i was getting, line 53 of main.cpp
-server_options_pointer->static_handlers[statement.at(1)] = config_line->child_block_;
+server_options_pointer->static_handlers[statement.at(1)] = config_line->child_block_.get();

**Comment by andykuang1** [comment]
You have to update the submodule so that it works properly.

**Comment by mattdrag** [comment]
Oh got it. Yeah now it works

**Pull request merged**
